#!/usr/bin/env python3

from rich import print
from rich.prompt import Prompt
import os

OPTIONS = [
    ["Check Data Integrity", ["pnpm vitest run src/tests/check_data_shape.test.ts"]],
    [
        "Ramayanam",
        [
            "cd data/ramayanam/",
            "uv run get_json.py",
        ],
    ],
    [
        "Bhagvad Gita",
        [
            "cd data/bhagavadgita",
            "uv run extract.py",
        ],
    ],
]


def main():
    print("[bold yellow]Generate JSON Files for:[/]")
    for i, option in enumerate(OPTIONS):
        print(f"[blue]{i+1}. {option[0]}[/]")
    print(f"[blue]e. Exit[/]")
    CHOICES = [str(i + 1) for i in range(len(OPTIONS))]
    CHOICES.append("e")
    choice = Prompt.ask("Choose an option", choices=CHOICES)
    if choice == "e":
        return
    command_info = OPTIONS[int(choice) - 1]
    command = " && ".join(command_info[1])
    os.system(command)
    if len(command_info) == 3:
        print(command_info[2])


if __name__ == "__main__":
    main()
