name: App Checks

on:
  push:
    branches:
      - main

env:
  CACHE_URL_KEY: ${{ secrets.CACHE_URL_KEY }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use iNode.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          run_install: true
          version: 10
      - run: |
          npx vite-node src/utils/text_data_invalidate.ts --verbose
